### ISSUE TITLE
Site functional?

### ISSUE THREAD

**Issue by wuehler** [okwme/doneth#32]
I was one of the mentors at the hackathon.. I really liked your project a lot for lots of reasons but am unable to get it to work now? Is the current live site meant to be functional?

**Comment by okwme** [comment]
Hi @wuehler yes it's working for me, i just deployed a new contract, added and then withdrew funds.

Do you have metamask installed and is the wallet unlocked? We haven't added any fallback dialog yet, so without those you only see a loading screen upon landing.

Can you tell us more what doesn't seem to be working?

**Comment by wuehler** [comment]
Yes, I have metamask (have been using it a long time).. when I try to deploy the popup says to unlock the wallet.. but my wallet is unlocked.

**Comment by okwme** [comment]
hmm, that's strange. i don't know why it might affect it but can you tell me which browser and network you're using?

**Comment by wuehler** [comment]
Chrome, mainnet

**Comment by wuehler** [comment]
I just locked, unlocked metamask. Then refreshed the page. Still says to unlock wallet. You'll get lots of attention to the site on Friday so hoping to help troubleshoot this ;)

**Comment by okwme** [comment]
@wuehler i've just deployed a debugger that prints wallet info, can you hard refresh and let me know what you see (thanks for the heads up btw!)

**Comment by okwme** [comment]
@wuehler oof i found it, we weren't whitelisting mainnet network id. THANK YOU FOR NOTICING!!!

**Comment by TrevorJTClarke** [comment]
@wuehler thank you!! Appreciate the testing!

**Comment by okwme** [comment]
working now, noticing that gas price estimates for mainnet are really low tho, transactions didn't go through in 50 blocks and failed, closing this and making a new issue to increase gas price

**Comment by wuehler** [comment]
Yeah it had metamask suggesting 20 Gwei.. i was able to put it through at 1 Gwei. Look into how you are estimating gas... Also, what are you using for your fiat price api?

**Comment by okwme** [comment]
oh really? i got a 50 block timeout at 10 Gwei, suggestion was 1 Gwei.
Those are coming from metamask directly though, if i used web3 to make the
predictions myself it would be the same mechanism as metamask, wouldn't it?
would you recommend another method for gas estimate and gas price estimate?
We're using cryptocompare's api for the fiat price, are you seeing sth
inaccurate? seems to be ~$1 off from coincap and almost same as coinbase.

**Comment by wuehler** [comment]
INFURA has a fiat/crypto api: http://docs.infura.apiary.io/

Could gain points using and mentioning it on Friday ;)

**Comment by wuehler** [comment]
regarding gas estimates, not sure.. will have to look into that

**Comment by okwme** [comment]
aha thanks for the tip!
would be cool if yall offered multiple currency rates in a single call though 😬

**Comment by wuehler** [comment]
I'll pass that feedback on
