### ISSUE TITLE
unused variables

### ISSUE THREAD

**Issue by davidp94** [okwme/doneth#47]
https://github.com/okwme/doneth/blob/fc0e0768ad518d8457df28f3fb63e40b945b8a3b/contracts/Doneth.sol#L43

https://github.com/okwme/doneth/blob/fc0e0768ad518d8457df28f3fb63e40b945b8a3b/contracts/Doneth.sol#L39-L40

**Comment by okwme** [comment]
Hi @davidp94 thanks for taking a look at the code! That's an old test version of the contract and you're quite right those are unused vars. In the live version of the contracts (originally available at https://github.com/defactoknife/doneth-truffle but currently being merged into this repo) they were also properly labeled as unused. 

They were intended for a possible future version of the contract which incremented new shares to project members on a recurring time scale. This would ensure something like eventual equality based on time associated with the project. At this point I think we will consider it out of scope so should probably remove them, thank you for pointing them out again. And thanks for looking through the code in general! We welcome you to make new issues on anything else you may find : )
