### ISSUE TITLE
Generic Modal for Forms

### ISSUE THREAD

**Issue by TrevorJTClarke** [okwme/doneth#51]
Modals!
Build out a UI matching comp, allowing users to see forms & interact with them. Must be responsive.

Example:
![doneth-admin-utils_v1b](https://user-images.githubusercontent.com/2633184/32201367-dc4f57c4-bd93-11e7-9982-8a414747d49a.jpg)

**Comment by okwme** [comment]
love the use of modals
i think we could utilize the store to trigger them to give better feedback on transactions tho
i'm gonna add myself and start working on an update
