### ISSUE TITLE
limit title length on contract

### ISSUE THREAD

**Issue by okwme** [okwme/doneth#58]
could reduce deploy gas cost

**Comment by okwme** [comment]
did some trials with this. right now we're getting warnings on deploy that the contract is so large it might not go through a single transaction (~5.5M gas). if we remove all the strings entirely it reduces down to ~4.5M. I made a branch to test out a contract that relied on events for keeping track of strings, but when using a string to deploy it doesn't really change anything. i tried limiting string length but ran into some troubles converting back and forth between bytes32[], bytes32[11], and string (where 11 is a string limit). would be good to decide on a limit and test contract size with a hard limit on bytes32[] to see if it makes a big price diff.

**Comment by TrevorJTClarke** [comment]
Is it the difficulty of converting back and forth to a string? bytes32 seems like a good way to go, I did some other tests on another contract, seemed to reduce cost by a good amount. I'm also curious if possibly logic needs to shift to another contract?
