### ISSUE TITLE
Transactions list update for new events

### ISSUE THREAD

**Issue by TrevorJTClarke** [okwme/doneth#61]
Tons of new events/logs!

Need to implement items for:

- [x] RemoveShare
- [x] Division
- [x] ChangePrivilege
- [x] ChangeContractName
- [x] ChangeMemberName
- [x] ChangeSharedExpense
- [x] WithdrawSharedExpense

**Comment by okwme** [comment]
started working on these but realized we don't have actions for change privilege or change contract name yet. think that the change privilege could be combined with allocate shares by just re-using the add member dialog. i made a contract call to combine updating name, shares and admin privileges on members so we could knock all of them out together : )

after the new modal system is running i'll work on combining the member form to be used for adding as well as editing

**Comment by okwme** [comment]
isse #69

**Comment by TrevorJTClarke** [comment]
@okwme the transactions list is looking awesome!!
