### ISSUE TITLE
Make Deposit (Add Funds) Doesn't store properly

### ISSUE THREAD

**Issue by TrevorJTClarke** [okwme/doneth#72]
Not sure whats causing it, but nothing im changing in transactions or data in sendTransaction object will make this work.

Steps to replicate:
1. Use "Add Funds" on any network (tried local, ropsten & rinkeby)
2. use any transaction settings
3. wait for confirmations, see nothing changed in contract total amount

NOTE: I am completely able to send funds directly to contract address, and the transfer is fine.
Any thoughts?

REF:
https://github.com/okwme/doneth/blob/master/src/store/actions.js#L310

**Comment by defactoknife** [comment]
I googled around, and it seems like you are supposed to use sendTransaction() in tandem with function calls. 

See:
https://ethereum.stackexchange.com/questions/8736/how-to-call-my-contracts-function-using-sendtransaction
http://ethdocs.org/en/latest/contracts-and-transactions/accessing-contracts-and-transactions.html
https://ethereum.gitbooks.io/frontier-guide/content/interacting_contract.html

There's also this interesting Stack Exchange answer about calls vs. transactions:
https://ethereum.stackexchange.com/questions/765/what-is-the-difference-between-a-transaction-and-a-call?newreg=fa9e4b13de434ad39fe0e63f191da0db

**Comment by okwme** [comment]
hmm very weird it works fine for me
Just used the popup GUI to donate 0.1 Eth to http://localhost:8080/0x913dbf4cafb365a605D12852C8f93B9820309a70 (on rinkeby)

Do you see any changes on your contract after refreshing page? any errors in logs?

**Comment by okwme** [comment]
gonna close this unless you still see the error?
